{lib, ...}:
with lib;
with lib.capybara; {
  capybara = {
    openssh.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF3/1HWL3C9D7+w4Et1zrGdJVTX27ibiRsITpe9rUCUw mtaku3@xanthus"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGqWtYuMBU25Yff5YDSQ0BaeljdTwK8t2HJq5U7cKD/Y Generated By Termius"
    ];

    app.dev = {
      zsh.enable = true;
      neovim = enabled;
      git = {
        enable = true;
        username = "mtaku3";
        email = "me@mtaku3.com";
      };
      tmux = enabled;
    };
  };

  home.stateVersion = "25.05";
}
