# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  networking.hostId = "0da9a9be";

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "ehci_pci" "virtio_pci" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  boot.loader.grub = {
    enable = true;
    device = "/dev/vda";
    zfsSupport = true;
  };
  boot.zfs.devNodes = "/dev/disk/by-path";

  boot.initrd.postResumeCommands = lib.mkAfter ''
    zfs rollback -r rpool/local/root@blank
  '';

  fileSystems."/" = {
    device = "rpool/local/root";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "rpool/local/nix";
    fsType = "zfs";
  };

  fileSystems."/persist" = {
    device = "rpool/safe/persist";
    fsType = "zfs";
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/ba93e854-d6a6-4dde-abf2-e8c39b253e14";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/232ed49f-6325-4cf5-9b94-14efdb23d291";}
  ];

  networking = {
    useDHCP = false;
    interfaces.ens3 = {
      ipv4.addresses = [
        {
          address = "153.120.5.92";
          prefixLength = 23;
        }
      ];
      ipv6.addresses = [
        {
          address = "2401:2500:102:2119:153:120:5:92";
          prefixLength = 64;
        }
      ];
    };
    defaultGateway = {
      address = "153.120.4.1";
      interface = "ens3";
    };
    defaultGateway6 = {
      address = "fe80::1";
      interface = "ens3";
    };
    nameservers = ["1.1.1.1" "8.8.8.8" "2606:4700:4700::1111" "2001:4860:4860::8888"];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
