# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
    inputs.disko.nixosModules.disko
    ./disko-config.nix
  ];

  networking.hostId = "0da9a9be";

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "ehci_pci" "virtio_pci" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  boot.loader.grub.enable = true;
  boot.zfs.devNodes = "/dev/disk/by-path";

  boot.initrd.postResumeCommands = lib.mkAfter ''
    zfs rollback -r rpool/local/root@blank
  '';

  fileSystems."/persist".neededForBoot = true;

  networking = {
    useDHCP = false;
    interfaces.ens3 = {
      ipv4.addresses = [
        {
          address = "153.120.5.92";
          prefixLength = 23;
        }
      ];
      ipv6.addresses = [
        {
          address = "2401:2500:102:2119:153:120:5:92";
          prefixLength = 64;
        }
      ];
    };
    defaultGateway = {
      address = "153.120.4.1";
      interface = "ens3";
    };
    defaultGateway6 = {
      address = "fe80::1";
      interface = "ens3";
    };
    nameservers = ["1.1.1.1" "8.8.8.8" "2606:4700:4700::1111" "2001:4860:4860::8888"];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
