{lib, ...}:
with lib;
with lib.capybara; {
  capybara = {
    openssh.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF3/1HWL3C9D7+w4Et1zrGdJVTX27ibiRsITpe9rUCUw mtaku3@xanthus"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGqWtYuMBU25Yff5YDSQ0BaeljdTwK8t2HJq5U7cKD/Y Generated By Termius"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFeoxn+NNjlbJPZYGUjH61Vcybh2o77OiWO0DY2iE8Br usr0200797@TMEN0081"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHuJO4G2OQp/MoxY76GefdqieTnmka5nbiLuoIkMBgBK matsushita@sl0351.local"
    ];

    app = {
      dev = {
        claude-code = enabled;
        zsh = {
          enable = true;
        };
        neovim = enabled;
        git = {
          enable = true;
          username = "mtaku3";
          email = "me@mtaku3.com";
          signingKey = "4DB490B409F22369";
          signByDefault = true;
        };
        gh = enabled;
        tmux = enabled;
        gpg = enabled;
        devbox = enabled;
        termius = enabled;
      };
    };

    impermanence = {
      enable = true;
      name = "/persist/home/mtaku3";
      directories = [
        "Downloads"
        "Music"
        "Pictures"
        "Documents"
        "Videos"
        ".gnupg"
        ".ssh"
        "Workspaces"
      ];
      files = [
        ".local/state/nvim/trust"
      ];
      allowOther = true;
    };

    agenix = enabled;
  };

  home.stateVersion = "25.05";
}
