{
  lib,
  config,
  ...
}:
with lib;
with lib.capybara; {
  capybara = {
    openssh.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF3/1HWL3C9D7+w4Et1zrGdJVTX27ibiRsITpe9rUCUw mtaku3@xanthus"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGqWtYuMBU25Yff5YDSQ0BaeljdTwK8t2HJq5U7cKD/Y Generated By Termius"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFeoxn+NNjlbJPZYGUjH61Vcybh2o77OiWO0DY2iE8Br usr0200797@TMEN0081"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHuJO4G2OQp/MoxY76GefdqieTnmka5nbiLuoIkMBgBK matsushita@sl0351.local"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFjPejXoTRBIiJ4a7w6bOKdOhkE8Ur0s8d8GIP/d/2Mx mtaku3@hermes"
    ];

    app = {
      dev = {
        claude-code = {
          enable = true;
          preStart = ''
            ESA_ACCESS_TOKEN=$(cat ${config.age.secrets."cc-secrets/esa-access-token".path})
            export ESA_ACCESS_TOKEN
            MEM0_API_KEY=$(cat ${config.age.secrets."cc-secrets/mem0-api-key".path})
            export MEM0_API_KEY
          '';
        };
        codex = {
          enable = true;
          # preStart left empty; codex authenticates via `codex login`.
        };
        zsh = {
          enable = true;
        };
        neovim = enabled;
        git = {
          enable = true;
          username = "mtaku3";
          email = "me@mtaku3.com";
          signingKey = "C29192ED1ABAAF1073F3B4DB6EBE5C8A537E7406";
          signByDefault = true;
        };
        gh = enabled;
        glow = enabled;
        tmux = enabled;
        gpg = {
          enable = true;
          importSubkeys = true;
          keyId = "C29192ED1ABAAF1073F3B4DB6EBE5C8A537E7406";
        };
        devbox = enabled;
        termius = enabled;
        kube-cli = {
          enable = true;
          masterAddress = "https://192.168.10.102:6443";
        };
      };
    };

    impermanence = {
      enable = true;
      name = "/persist/home/mtaku3";
      directories = [
        "Downloads"
        "Music"
        "Pictures"
        "Documents"
        "Videos"
        ".gnupg"
        ".ssh"
        "Workspaces"
        ".vscode-server"
      ];
      files = [
        ".local/state/nvim/trust"
      ];
      allowOther = true;
    };

    agenix = {
      enable = true;
      userPubkeys = [
        "age1fje5j6rwhvd6kzd0ttedtaaslppx499glwqrty0wj0ryysrqzghs4mc503"
      ];
    };
  };

  home.stateVersion = "25.05";
}
